"""Export the faculty course specification workbook to Markdown.

    python scripts/export_spec_md.py

The workbook stays the authoritative document — this produces the readable version that
renders on GitHub. Re-run it whenever the workbook changes, or the two will drift and the
website will quietly show stale marks.

Formula cells are exported as their cached value, so open and save the workbook in Excel
before running this if you have edited formulas outside Excel.
"""
from __future__ import annotations

import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "course" / "spec" / "Course_Specification_ITCS355_merged.xlsx"
OUTPUT = ROOT / "course" / "spec" / "course-specification.md"

# Sheets the faculty owns, versus sheets added during course design.
ORIGINAL = {
    "Course Information", "CLOs", "CLO & PLO Alignment", "Teaching Plan",
    "Teaching Method", "Evaluation Method", "Grading Criteria", "Rubric Scoring",
}


def cell_text(value) -> str:
    """Render one spreadsheet cell as plain text, with empty cells becoming blanks."""
    if value is None:
        return ""
    text = str(value).strip().replace("\n", "<br>").replace("|", "\\|")
    return text


def sheet_to_markdown(worksheet) -> list[str]:
    """Render one worksheet as the lines of a Markdown table."""
    rows: list[list[str]] = []
    for row in worksheet.iter_rows():
        cells = [cell_text(cell.value) for cell in row]
        while cells and cells[-1] == "":
            cells.pop()
        rows.append(cells)

    while rows and not any(rows[-1]):
        rows.pop()
    if not rows:
        return ["_(empty sheet)_", ""]

    width = max(len(row) for row in rows)
    rows = [row + [""] * (width - len(row)) for row in rows]

    # A single wide merged cell across the top is a title, not a table header.
    lines: list[str] = []
    start = 0
    if sum(1 for cell in rows[0] if cell) == 1 and len(rows) > 1:
        lines += [f"_{rows[0][0]}_", ""]
        start = 1

    header = rows[start]
    if not any(header):
        header = [f"Col {index + 1}" for index in range(width)]
    else:
        start += 1

    lines.append("| " + " | ".join(header or " " for header in header) + " |")
    lines.append("|" + "|".join(["---"] * width) + "|")
    for row in rows[start:]:
        lines.append("| " + " | ".join(cell or " " for cell in row) + " |")
    lines.append("")
    return lines


def uncached_formulas() -> list[str]:
    """Cells holding a formula that carries no cached result."""
    formulas = openpyxl.load_workbook(WORKBOOK, data_only=False)
    values = openpyxl.load_workbook(WORKBOOK, data_only=True)
    stale = []
    for name in formulas.sheetnames:
        fws, vws = formulas[name], values[name]
        for row in fws.iter_rows():
            for cell in row:
                if isinstance(cell.value, str) and cell.value.startswith("="):
                    if vws[cell.coordinate].value is None:
                        stale.append(f"{name}!{cell.coordinate}  {cell.value}")
    return stale


def main() -> int:
    """Convert the specification workbook into Markdown so it renders on GitHub."""
    if not WORKBOOK.exists():
        print(f"missing workbook: {WORKBOOK}")
        return 1

    workbook = openpyxl.load_workbook(WORKBOOK, data_only=True)

    # A formula whose cached value is missing reads as None here and would publish as an
    # empty cell — a total silently vanishing from the specification. The university
    # system exports workbooks in exactly that state, so check rather than trust.
    stale = uncached_formulas()
    if stale:
        print("formula cells have no cached value; they would export blank:")
        for ref in stale:
            print(f"  {ref}")
        print("Open the workbook in Excel and save it, or replace these with literals.")
        return 1

    out: list[str] = [
        "# ITCS355 — Course Specification",
        "",
        "> Generated from "
        "[`Course_Specification_ITCS355_merged.xlsx`](Course_Specification_ITCS355_merged.xlsx) "
        "by `scripts/export_spec_md.py`. **The workbook is authoritative** — edit it, then "
        "re-run the exporter. Do not edit this file by hand.",
        "",
        "Sheets marked *faculty* are the original template, unmodified except for five "
        "corrected rubric descriptors. Sheets marked *added* were produced during course "
        "design and can be removed before faculty submission.",
        "",
        "## Contents",
        "",
    ]

    for name in workbook.sheetnames:
        origin = "faculty" if name in ORIGINAL else "added"
        anchor = name.lower().replace(" ", "-").replace("&", "").replace("--", "-")
        out.append(f"- [{name}](#{anchor}) — *{origin}*")
    out.append("")

    for name in workbook.sheetnames:
        origin = "faculty template" if name in ORIGINAL else "added during course design"
        out += ["---", "", f"## {name}", "", f"*{origin}*", ""]
        out += sheet_to_markdown(workbook[name])

    OUTPUT.write_text("\n".join(out))
    print(f"wrote {OUTPUT.relative_to(ROOT)}  ({len(workbook.sheetnames)} sheets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
